# Generated by Django 5.2.8 on 2025-11-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_campaign_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='icon',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='campaignmembership',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Player'), (1, 'Master'), (2, 'Owner')], default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, default='exists'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='telegram_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
