# Generated by Django 5.2.8 on 2025-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_alter_campaign_icon_alter_campaignmembership_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
